### ISSUE TITLE
Cannot Edit Logo image in the queue

### ISSUE THREAD

**Issue by PichapopRo** [pannlnwza/queue-management#192]
The preview doesn't show anything and after pressing save the image didn't save

![image](https://github.com/user-attachments/assets/7fd5bc67-155a-44e2-adfd-d1321e21bd64)

**Comment by tarothanawat** [comment]
![image](https://github.com/user-attachments/assets/ca2fed8f-5f7f-40c0-83ee-3219d7dbb894)
Now our applications doesn't have previews. Thanks for pointing this out.
