### ISSUE TITLE
No top 3 queues available despite having queues

### ISSUE THREAD

**Issue by KhunakornP** [pannlnwza/queue-management#193]
## **Bug**
There are no queues shown on the main page.

## **Additional Information**
Location is blocked by my browser.

## **User Specifications**
OS: Windows 10
Browser: Chrome Version 131.0.6778.86

## **Screenshots**
![no queues](https://github.com/user-attachments/assets/ee6105c3-bb98-4c04-b75d-ba59959adfa0)
![q](https://github.com/user-attachments/assets/b0a4d110-ef76-48e2-b3f0-6c6464c01462)

**Comment by pannlnwza** [comment]
Thank you for reporting. It looks like there is a bug causing the top queues to not display when the location is blocked by the browser, even though they should still appear when there are participants in the queue.

We’re currently looking into the cause of this issue and will work on a fix.

**Comment by pannlnwza** [comment]
We’ve fixed the issue! It turned out that one of our team members accidentally put the element in the wrong if statement. 😭
