### ISSUE TITLE
Invalid Time Configuration: App Allows Closing Time Earlier Than Opening Time

### ISSUE THREAD

**Issue by Napoldej** [pannlnwza/queue-management#195]
<img width="642" alt="Screenshot 2567-11-24 at 22 37 21" src="https://github.com/user-attachments/assets/66666089-4608-4da4-be22-b5ce313d965f">

Why does the app allow setting a closing time earlier than the opening time, or am I misunderstanding?

**Comment by tarothanawat** [comment]
This is actually not a bug. Our application allows overnight queues eg. open at 9PM, closes at 4AM. Thanks for pointing this out.
