### ISSUE TITLE
Form Data Lost After Navigating Back During Queue Creation

### ISSUE THREAD

**Issue by SunthornK** [pannlnwza/queue-management#196]
While creating a queue, clicking the 'Back' button clears all the information I entered. I have to start over, which is frustrating. The data should stay saved when I go back and forth using the 'Back' and 'Next' buttons.

**Comment by pannlnwza** [comment]
I’ve fixed it so the data stays saved when you go back and forth between the Previous and Next buttons. Thanks for pointing that out! :)
