### ISSUE TITLE
Is logo or image can really use?

### ISSUE THREAD

**Issue by Napoldej** [pannlnwza/queue-management#199]
<img width="926" alt="Screenshot 2567-11-24 at 23 04 37" src="https://github.com/user-attachments/assets/e02ab01b-1b22-45c1-8abf-5f167e8c051a">
<img width="958" alt="Screenshot 2567-11-24 at 23 04 43" src="https://github.com/user-attachments/assets/b6efdc29-2841-4b3e-9035-4040c5b012a8">

I have never seen the image or logo on any page, and also in the network tab, I got 404 status on the image task.

**Comment by tarothanawat** [comment]
![image](https://github.com/user-attachments/assets/3076859e-8200-41a4-b607-7ede8d585f0b)
![image](https://github.com/user-attachments/assets/b341e9da-ec30-4f72-ad07-9d23efac6677)

Now we upload file to AWS, so this problem has been fix! Thanks for pointing it out.
