### ISSUE TITLE
I can insert and update the string in phone number field.

### ISSUE THREAD

**Issue by Napoldej** [pannlnwza/queue-management#200]
<img width="820" alt="Screenshot 2567-11-24 at 23 19 39" src="https://github.com/user-attachments/assets/bffb5b95-7dda-47d4-bf6e-ec08f57de87e">

How can I insert and update my profile with the string in the phone number field?

**Comment by tarothanawat** [comment]
![image](https://github.com/user-attachments/assets/06d74e82-e05e-46e9-9bd7-8cc5dee4a2ca)
This has been fixed. Thanks for pointing this out! 👍
