### ISSUE TITLE
Waiting participants show in "Today" but not in "This week"

### ISSUE THREAD

**Issue by colarrbear** [pannlnwza/queue-management#206]
### Steps to Reproduce  
<img width="100" alt="image" src="https://github.com/user-attachments/assets/351366cd-660b-4b58-a1f6-029df55dafa5">

Participants page on left hand side.

### Expected Behavior  
I guess it also needs to be shown in *This week* too if it's in today. However it exist in This month, This year, All time as expected.

### Environment  
- **OS:** MacOS 14.6.1
- **Browser (if relevant):** Arc

<img width="1709" alt="image" src="https://github.com/user-attachments/assets/fbef8bf0-3d97-40a7-b544-3b7ade48ca7e">
<img width="1610" alt="image" src="https://github.com/user-attachments/assets/8b39a5a0-f4bb-4877-aed9-c28a15eb8304">

**Comment by tarothanawat** [comment]
![image](https://github.com/user-attachments/assets/3f323751-cf7e-4de4-bcc8-6ad0fe8bf6cd)
![image](https://github.com/user-attachments/assets/407861ae-1dfd-4936-93fe-afa4b9dbb16a)
![image](https://github.com/user-attachments/assets/a7031f67-9d4c-48ea-9e5e-f89ee13b3ecb)
![image](https://github.com/user-attachments/assets/79fb1ea8-e484-4a82-b99e-f45ff3e8d190)
![image](https://github.com/user-attachments/assets/98424d2e-d4f0-477e-8277-4a37e616d90d)


You actually made us realize that the function was just a placeholder. We already fixed it. Thankyou for pointing this out 👍 .
