### ISSUE TITLE
Serve button is not work? 

### ISSUE THREAD

**Issue by colarrbear** [pannlnwza/queue-management#207]
<img width="1534" alt="image" src="https://github.com/user-attachments/assets/d1655ec1-577b-49ed-b266-3ec2696f1c8c">
(Navigate by Home logo > Serve button)
Serve is not work? 
<br></br>
After clicked for multiple time, I've checked in *Participants* too but show no one is in *Serving*.
(Navigate by Home logo > Serve button)
<img width="1710" alt="image" src="https://github.com/user-attachments/assets/1dcda754-141f-4091-84c6-4aab86ac7c45">

**Comment by tarothanawat** [comment]
![image](https://github.com/user-attachments/assets/5f23231c-2e90-47e0-8444-8e0b73eac338)
![image](https://github.com/user-attachments/assets/ef3ea00d-e2e6-4d6f-8cff-51f06b681173)
![image](https://github.com/user-attachments/assets/fe2d821e-bad6-4616-b931-d5d1044650b1)


The bug has been fix earlier in the development phase, so I can't replicate it. Thanks for pointing this out anyways 😺 .
