### ISSUE TITLE
Can't look into insights of summary page

### ISSUE THREAD

**Issue by colarrbear** [pannlnwza/queue-management#208]
After customer waiting for a while 

<img width="1710" alt="image" src="https://github.com/user-attachments/assets/a3626be9-5731-4165-950f-b6f1a3ebcd6f">
(Participants tab)
<br></br>
Data for the longest waiting time do not show in dashboard
<img width="1603" alt="image" src="https://github.com/user-attachments/assets/eea19de1-4085-477f-81d0-f588accd27bc">
(Statistics tab)

**Comment by tarothanawat** [comment]
The participant is marked as no show. So their stats doesn't count towards the overall statistics of the queue. Thanks for pointing it out!
