### ISSUE TITLE
Queue is close but not close.

### ISSUE THREAD

**Issue by colarrbear** [pannlnwza/queue-management#209]
<img width="1710" alt="image" src="https://github.com/user-attachments/assets/8ca828e8-28c6-419f-bcf0-5ef235f61c6f">

After the designated closing time for this queue, it remains open and allows for the addition of new participants.

<img width="1710" alt="image" src="https://github.com/user-attachments/assets/51508a5e-e1b3-4f2b-86b5-5828a328c9ac">

It still shown in land page T_T
<img width="1710" alt="image" src="https://github.com/user-attachments/assets/bfd16b75-24ce-472f-aa47-df2e2d8ba9cc">

**Comment by tarothanawat** [comment]
![image](https://github.com/user-attachments/assets/c0a1fd05-b34c-4ab9-842a-3de490cde483)
![image](https://github.com/user-attachments/assets/badf4dd4-f938-4d57-b1d4-be70c8602fa1)
![image](https://github.com/user-attachments/assets/fc1009c1-14f8-4a18-9ca1-5b2b16baeb21)

Closing the queue is now handled correctly. Thanks for finding the bug!
