### ISSUE TITLE
No Show user still appear in landing page.

### ISSUE THREAD

**Issue by colarrbear** [pannlnwza/queue-management#210]
<img width="1710" alt="image" src="https://github.com/user-attachments/assets/65b94913-714d-4807-ab5f-462a92708023">

<img width="1710" alt="image" src="https://github.com/user-attachments/assets/ff5c990e-dbf4-40f0-ac3a-71ef6571b8fc">

I’ve removed the user for being a "No Show," but they still appear as waiting in the queue on the landing page.

**Comment by tarothanawat** [comment]
![image](https://github.com/user-attachments/assets/0669e8fd-7b41-46b1-ae81-adf385b17eb4)
![image](https://github.com/user-attachments/assets/6a168870-47c9-4cdd-a299-6a74ac93b02d)


The problem has been fixed👍. Thanks for pointing it out!
